### ISSUE TITLE
Don't identify SRP groups solely by their size

### ISSUE THREAD

**Issue by agilecohix** [agilebits/srp#12]
Although at the moment we use DH groups exclusively from RFC 3526, which specifies only one group of each size, we may find ourselves seeking out different 4096 groups. So we shouldn't be identifying groups in our code exclusively by their size as we do with GetGroupName().

Copied from https://github.com/agilebits/op/issues/144

**Comment by jpgoldberg** [comment]
Old, no longer applicable issue.
