### ISSUE TITLE
Remove 1024 bit group.

### ISSUE THREAD

**Issue by jpgoldberg** [agilebits/srp#2]
It is safer to not even have the dangerously weak parameters in the code. I don't know what testing we use that for, but we should ditch the group unless there is a compelling reason to keep it.

We don't know how other parts of the code will change, and so even if there are no downgrade attacks possible now, a small change in logic years from now might enable one. For example, see the recent downgrade attacks on TLS that led to use of "export" ciphers from the 1990s. The lesson people are taking is to not even have such things in the code at all.

**Comment by jpgoldberg** [comment]
https://wiki.mozilla.org/Identity/AttachedServices/KeyServerProtocol#SRP_Protocol_Details contains test vectors for a much safer 2048-bit group. We could replace our test with those test vectors.

**Comment by julie-ab** [comment]
Praise various deities that this has been closed. I've been watching the SRP re-write and am grateful you don't have anything nearly that short in there!

**Comment by jpgoldberg** [comment]
We aren't (yet) actually using the code from this repo anywhere. So the 1024-bit group is still lurking around a lot of our code.
