### ISSUE TITLE
Don't use group size as group identifier

### ISSUE THREAD

**Issue by jpgoldberg** [agilebits/srp#8]
At the moment we are only considering one group of each size, but there may someday be cause to want to use a different 4096 bit group. Our group lookup keys shouldn't just be those integers representing the size.

**Comment by jpgoldberg** [comment]
Never mind. In this repo the map keys are strings.

**Comment by rickfillion** [comment]
It's also consistent with how OpenSSL does it via `SRP_get_default_gN`, no?
